### PR TITLE
feat: add check for permutation

### PR DESCRIPTION
**Pull request by sebffischer**

### CODE REVIEW

**Comment by sebffischer** [comment]
The only thing I am unhappy with is the `any(x != y)`, there should be a faster way to test this. Any suggestions? But I could not quickly find a function that does that. At least identical might be tricky with factors. Maybe some version of all.equal?

**Comment by mllg** [comment]
A more general question: What is the intended behaviour if `x` or `y` have duplicated values? I'm a bit confused by the comment 
```
   # now this is checkSetEqual(..., ordered = TRUE) with additional sorting.
```

**Comment by mllg** [comment]
Also, `x != y` will not work with missing values.

**Comment by sebffischer** [comment]
Duplicated values are not treated special in any way or what exactly do you mean by that?

I think the comment regarding the checkSetEqual with ordered = TRUE is actually incorrect and should be removed. What I mean by that is that comparing [1, 2, 1] with [1, 1, 2] essentially turns into checking whether all [1, 1, 2] == [1, 1, 2]. This also shows how the duplicated values are being handled. 
 

Yes, but the `x !=  y` never contains missing values (they are dropped by the sort, see the comment).

**Comment by sebffischer** [comment]
Yes. Note that we check the length twice. 
1. To check the lengths of the full vectors. 
2. After sorting: To check whether the same amount of NAs was removed

Your example is captured in the first length check

**Comment by mllg** [comment]
Ok, got it now. I think you could clarify a bit in the documentation, but otherwise good to be merged.

**Comment by sebffischer** [comment]
I added some comments

**Comment by sebffischer** [comment]
@mllg

**Comment by sebffischer** [comment]
Can this be merged @mllg ?

**Pull request merged**
